---
title: "combine_data"
author: "blind"
date: "2024-07-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE}
library(purrr)
library(tidyr)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(psycho)
library(readxl)
library(GGally)
library(conflicted)
library(performance)
library(cowplot)
library(lme4)
library(lmerTest)
library(MASS) 
library(caret)
library(leaps)
```

```{r}
path<-"../../ppcc_iflu_data/data_exp_170005-v9"
list.files(path)

read_csvs_with_pattern <- function(path, pattern) {
  files <- list.files(path, pattern = pattern, full.names = TRUE)
  data_list <- map(files, read.csv)
  combined_data <- bind_rows(data_list)
  colnames(combined_data)<-tolower(colnames(combined_data))
  return(combined_data)
}

read_xls_with_pattern <- function(path, pattern) {
  files <- list.files(path, pattern = pattern, full.names = TRUE)
  data_list <- map(files, read_excel)
  combined_data <- bind_rows(data_list)
  colnames(combined_data)<-tolower(colnames(combined_data))
  return(combined_data)
}

pattern="11wd"
s_exp1 <- read_csvs_with_pattern(path, paste(pattern,".*\\.csv",sep=""))
s_exp1_et <- read_xls_with_pattern(file.path(path,"uploads/"), pattern)

#pattern="vg7n"
#s_exp2 <- read_csvs_with_pattern(path, paste(pattern,".*\\.csv",sep=""))
#s_exp2_et <- read_xls_with_pattern(file.path(path,"uploads/"), pattern)

pattern="1f8j"
digit_span <- read_csvs_with_pattern(path, paste(pattern,".*\\.csv",sep=""))

pattern="7oyj|9uw1|wxw8|qa8d"
battery <- read_csvs_with_pattern(path, paste(pattern,".*\\.csv",sep=""))

pattern="rsao"
lextale <- read_csvs_with_pattern(path, paste(pattern,".*\\.csv",sep=""))

pattern="m24c"
italian_lextale <- read_csvs_with_pattern(path, paste(pattern,".*\\.csv",sep=""))

pattern="3nvp"
autism <- read_csvs_with_pattern(path, paste(pattern,".*\\.csv",sep=""))

acoustic_data<-read.csv("acoustic_data_ppcc.csv")

removal <- data.frame(task = character(), 
                      value = numeric(), 
                      stringsAsFactors = FALSE)
```
```{r}
s_exp1_cleaned<-s_exp1%>%
  select(participant.private.id,spreadsheet.row,response,real_1_distractor_0,zone.type,display,audio,
         q1_image,q2_image,q3_image,q4_image,
         id,grouping_id,sorting,audio)%>%
  filter(zone.type=="response_button_image")%>%
  mutate(audio=tolower(audio),
         word_play = str_remove(str_extract(audio, "^[^_]+"), "\\.wav"),
         word_play_start = substr(word_play, 1, 3),
         stress_play = str_remove(str_extract(audio, "(?<=_)[^_]+"), "\\.wav"),
         response_word = str_extract(response, "(?<=\\d)[a-zA-Z]+(?=\\.jpeg)"),
         response_thing = str_extract(response, "(?<=\\D)\\d{2}(?=[a-zA-Z]+\\.jpeg)"),
         correct=if_else(response_word==word_play,1,0))%>%
  mutate(stress_play=if_else(stress_play=="p","Penultimate","Anti-penultimate"),
         q1_word= str_extract(q1_image, "(?<=\\d)[a-zA-Z]+(?=\\.jpeg)"),
         q2_word= str_extract(q2_image, "(?<=\\d)[a-zA-Z]+(?=\\.jpeg)"),
         q3_word= str_extract(q3_image, "(?<=\\d)[a-zA-Z]+(?=\\.jpeg)"),
         q4_word= str_extract(q4_image, "(?<=\\d)[a-zA-Z]+(?=\\.jpeg)"))%>%
 mutate(target_quantile=case_when(q1_word==word_play~1,
                                 q2_word==word_play~2,
                                 q3_word==word_play~3,
                                 q4_word==word_play~4),
       competitor_quantile = case_when(
      q1_word != word_play & str_detect(q1_word,word_play_start) ~ 1,
      q2_word != word_play & str_detect(q2_word,word_play_start) ~ 2,
      q3_word != word_play & str_detect(q3_word,word_play_start) ~ 3,
      q4_word != word_play & str_detect(q4_word,word_play_start) ~ 4))%>%
  rowwise() %>%
  mutate(distractor_1_quantile = {
    possible_values <- setdiff(1:4, c(target_quantile, competitor_quantile))
    sample(possible_values, 1)
  })%>%
  mutate(distractor_2_quantile = 10-sum(distractor_1_quantile,target_quantile,competitor_quantile))%>%
  ungroup()

s_exp1_cleaned<-s_exp1_cleaned%>%
  mutate(target = case_when(target_quantile == 1 ~ q1_word,
                            target_quantile == 2 ~ q2_word,
                            target_quantile == 3 ~ q3_word,
                            target_quantile == 4 ~ q4_word),
         competitor = case_when(competitor_quantile == 1 ~ q1_word,
                                competitor_quantile == 2 ~ q2_word,
                                competitor_quantile == 3 ~ q3_word,
                                competitor_quantile == 4 ~ q4_word),
         dist_1 = case_when(distractor_1_quantile == 1 ~ q1_word,
                                  distractor_1_quantile == 2 ~ q2_word,
                                  distractor_1_quantile == 3 ~ q3_word,
                                  distractor_1_quantile == 4 ~ q4_word),
         dist_2 = case_when(distractor_2_quantile == 1 ~ q1_word,
                                  distractor_2_quantile == 2 ~ q2_word,
                                  distractor_2_quantile == 3 ~ q3_word,
                                  distractor_2_quantile == 4 ~ q4_word))

```

```{r}
#eye-tracking clean up
s_exp1_et_cleaned<-s_exp1_et%>%
  select(participant_id,spreadsheet_row,type,time_stamp,
         time_elapsed,x_pred_normalised,y_pred_normalised,face_conf)%>%
  mutate(participant.private.id=participant_id,
         spreadsheet.row=spreadsheet_row)%>%
  select(!c(participant_id,spreadsheet_row))%>%
  filter(type=="prediction")
  
eye_fixations <- s_exp1_et_cleaned %>%
  left_join(s_exp1_cleaned)%>%
  na.omit()%>%
  filter(face_conf>.5)%>%
  mutate(x_pred_normalised=x_pred_normalised-.5,
         y_pred_normalised=y_pred_normalised-.5)

eye_fixations_kept <- s_exp1_et_cleaned %>%
  left_join(s_exp1_cleaned)%>%
  na.omit()%>%
  filter(face_conf>.5)%>%
  mutate(x_pred_normalised=x_pred_normalised-.5,
         y_pred_normalised=y_pred_normalised-.5)%>%
  filter(x_pred_normalised<1&x_pred_normalised>-1)%>%
  filter(y_pred_normalised<1&y_pred_normalised>-1)

nrow(eye_fixations_kept)/nrow(eye_fixations)

origin<-c(0,0)
s_exp1_data_all <- s_exp1_et_cleaned %>%
  left_join(s_exp1_cleaned)%>%
  na.omit()%>%
  filter(face_conf>.5)%>%
  mutate(x_pred_normalised=x_pred_normalised-.5,
         y_pred_normalised=y_pred_normalised-.5)%>%
  filter(x_pred_normalised<1&x_pred_normalised>-1)%>%
  filter(y_pred_normalised<1&y_pred_normalised>-1)%>%
  mutate(current_quadrant = case_when(
            x_pred_normalised < origin[1] & y_pred_normalised > origin[2] ~ q1_word,
            x_pred_normalised > origin[1] & y_pred_normalised > origin[2] ~ q2_word,
            x_pred_normalised < origin[1] & y_pred_normalised < origin[2] ~ q3_word,
            x_pred_normalised > origin[1] & y_pred_normalised < origin[2] ~ q4_word))%>%
  mutate(target_looks=if_else(current_quadrant==target,1,0),
         competitor_looks=if_else(current_quadrant==competitor,1,0),
         dist1_looks=if_else(current_quadrant==dist_1,1,0),
         dist2_looks=if_else(current_quadrant==dist_2,1,0))%>%
  group_by(participant.private.id,spreadsheet.row,stress_play)%>%
  mutate(time=time_stamp-min(time_stamp),
         time_rounded = round(time / 50) * 50)%>%
  mutate(time_rounded=time_rounded-1200)%>% #offset for experiment timing
  filter(time_rounded<1000&time_rounded>=0)


frame_rate_cut_off<-5
time_binning=50
all_data_cleaned_fr<-s_exp1_data_all%>%
  group_by(participant.private.id,word_play,stress_play)%>%
  mutate(count = n(),
            max_time = max(time_elapsed),
            frame_rate = count/max_time*1000)%>%
  ungroup()%>%
  group_by(participant.private.id)%>%
  mutate(median_frame_rate = median(frame_rate))%>%
  filter(median_frame_rate>=frame_rate_cut_off)%>%
  mutate(time_elapsed_rounded=time_binning*round((time_elapsed)/time_binning))

all_data_cleaned_fr%>%ggplot(aes(x=participant.private.id,y=median_frame_rate))+geom_point()
all_data_cleaned_fr_part<-all_data_cleaned_fr%>%filter(median_frame_rate>5)
length(unique(all_data_cleaned_fr_part))
length(unique(all_data_cleaned_fr))
```


```{r}
target_dir <- "../../ppcc_iflu_data/read_data"
dir.create(target_dir, showWarnings = FALSE)

write.csv(s_exp1, file.path(target_dir, "s_exp1.csv"), row.names = FALSE)
write.csv(s_exp1_data_all, file.path(target_dir, "s_exp1_data_all.csv"), row.names = FALSE)
write.csv(digit_span, file.path(target_dir, "digit_span.csv"), row.names = FALSE)
write.csv(battery, file.path(target_dir, "battery.csv"), row.names = FALSE)
write.csv(lextale, file.path(target_dir, "lextale.csv"), row.names = FALSE)
write.csv(italian_lextale, file.path(target_dir, "italian_lextale.csv"), row.names = FALSE)
write.csv(autism, file.path(target_dir, "autism.csv"), row.names = FALSE)
write.csv(acoustic_data, file.path(target_dir, "acoustic_data.csv"), row.names = FALSE)
write.csv(removal, file.path(target_dir, "removal.csv"), row.names = FALSE)
```
