---
title: "work_flow"
author: "blind"
date: "2024-04-15"
output: html_document
---

```{r setup, include=FALSE}
library(purrr)
library(tidyr)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(psycho)
library(readxl)
library(GGally)
library(conflicted)
library(performance)
library(cowplot)
library(lme4)
library(lmerTest)
library(MASS) 
library(caret)
library(leaps)
```

```{r}
path<-"../../ppcc_iflu_data/data_exp_170005-v9"
list.files(path)

read_csvs_with_pattern <- function(path, pattern) {
  files <- list.files(path, pattern = pattern, full.names = TRUE)
  data_list <- map(files, read.csv)
  combined_data <- bind_rows(data_list)
  colnames(combined_data)<-tolower(colnames(combined_data))
  return(combined_data)
}

read_xls_with_pattern <- function(path, pattern) {
  files <- list.files(path, pattern = pattern, full.names = TRUE)
  data_list <- map(files, read_excel)
  combined_data <- bind_rows(data_list)
  colnames(combined_data)<-tolower(colnames(combined_data))
  return(combined_data)
}

pattern="11wd"
s_exp1 <- read_csvs_with_pattern(path, paste(pattern,".*\\.csv",sep=""))
s_exp1_et <- read_xls_with_pattern(file.path(path,"uploads/"), pattern)

pattern="vg7n"
s_exp2 <- read_csvs_with_pattern(path, paste(pattern,".*\\.csv",sep=""))
s_exp2_et <- read_xls_with_pattern(file.path(path,"uploads/"), pattern)

pattern="1f8j"
digit_span <- read_csvs_with_pattern(path, paste(pattern,".*\\.csv",sep=""))

pattern="7oyj|9uw1|wxw8|qa8d"
battery <- read_csvs_with_pattern(path, paste(pattern,".*\\.csv",sep=""))

pattern="rsao"
lextale <- read_csvs_with_pattern(path, paste(pattern,".*\\.csv",sep=""))

pattern="m24c"
italian_lextale <- read_csvs_with_pattern(path, paste(pattern,".*\\.csv",sep=""))

pattern="3nvp"
autism <- read_csvs_with_pattern(path, paste(pattern,".*\\.csv",sep=""))


removal <- data.frame(task = character(), 
                      value = numeric(), 
                      stringsAsFactors = FALSE)
```

```{r}
library(conflicted)
battery_tidy<-battery%>%
  select(participant.private.id,tree.node.key,task.name,screen.name,screen.number,display,reaction.time,response,sound1,sound2,base1,base2,same)%>%
  filter(display=="block" &screen.name == "Screen 3")%>%
  mutate(responses=case_when(response == "'z'"~1,
                             response == "'m'"~0),
         correct=if_else(responses==same,1,0),
         difference=abs(base1-base2))

battery_tidy%>%ggplot(aes(x=reaction.time))+geom_histogram()+facet_wrap(participant.private.id~.)

mad_standard=3

battery_cleaned<-battery_tidy%>%
  #group_by(participant.private.id)%>%
  dplyr::filter(reaction.time>200)%>%
  mutate(log_rt=sqrt(reaction.time))%>%
  mutate(display_medians = median(log_rt),
         abs_distance = abs(display_medians-log_rt),
         mean_distance = mean(abs_distance),
         upper_mad = display_medians+(mean_distance*mad_standard),
         lower_mad = display_medians-(mean_distance*mad_standard))%>%
  group_by(participant.private.id)%>%
  mutate(participants_medians = median(log_rt))%>%
  dplyr::filter(log_rt<upper_mad &log_rt>lower_mad)


removal[nrow(removal) + 1, ] <- c("battery removal", 
                                  nrow(battery_tidy) - nrow(battery_cleaned))

battery_cleaned%>%ggplot(aes(x=log_rt))+
  geom_histogram()+
  geom_point(aes(x=upper_mad,y=0),color="red")+
  geom_point(aes(x=lower_mad,y=0),color="blue")+
  facet_wrap(participant.private.id~.)

battery_cleaned%>%ggplot(aes(x=factor(participant.private.id),y=participants_medians))+
  geom_point()+
  geom_point(aes(y=upper_mad,x=factor(participant.private.id)),color="red")+
  geom_point(aes(y=lower_mad,x=factor(participant.private.id)),color="blue")

battery_cleaned_part_agg<-battery_cleaned%>%
  group_by(participant.private.id)%>%
summarise(score=mean(correct))%>%
  ungroup()%>%
    mutate(medians = median(score),
           abs_distance = abs(medians-score),
           mean_distance = mean(abs_distance),
           upper_mad = medians+(mean_distance*mad_standard),
           lower_mad = medians-(mean_distance*mad_standard))

battery_cleaned_part_agg%>%
  ggplot(aes(x=factor(participant.private.id),y=score))+
  geom_point()+
  geom_point(aes(x=factor(participant.private.id),y=upper_mad),color="red")+
  geom_point(aes(x=factor(participant.private.id),y=lower_mad),color="red")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))

battery_cleaned_part_agg_keep<-battery_cleaned_part_agg%>%
  filter(score<upper_mad & score>lower_mad)

battery_cleaned_item_agg<-battery_cleaned%>%
  group_by(difference,participant.private.id)%>%
summarise(score=mean(correct))%>%
  ungroup()%>%
    mutate(medians = median(score),
           abs_distance = abs(medians-score),
           mean_distance = mean(abs_distance),
           upper_mad = medians+(mean_distance*mad_standard),
           lower_mad = medians-(mean_distance*mad_standard))

battery_cleaned_item_agg%>%
  ggplot(aes(x=factor(difference),y=score))+
  geom_boxplot()+
  geom_point()+
  geom_point(aes(x=factor(difference),y=upper_mad),color="red")+
  geom_point(aes(x=factor(difference),y=lower_mad),color="red")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))

#battery_cleaned<-battery_cleaned%>%filter(difference<35)
```
```{r}
battery_agg2<-battery_cleaned%>%
  group_by(participant.private.id, task.name) %>%
  summarize(score=mean(correct))

battery_agg2%>%ggplot(aes(x=task.name,y=score,color=factor(task.name)))+
  geom_boxplot()+
  geom_jitter()+
  theme_minimal()

battery_agg<-battery_cleaned%>%
  mutate(
    hit = if_else(same == 1 & responses == 1L, 1L, 0L),
    f_a = if_else(same == 0 & responses == 1L, 1L, 0L),
    miss = if_else(same == 0 & responses == 0L, 1L, 0L),
    c_r = if_else(same == 1 & responses == 0L, 1L, 0L))%>%
  group_by(participant.private.id, task.name) %>%
  summarize(
    score=mean(correct)+.5,
    hit_count = sum(hit)+.5,
    f_a_count = sum(f_a)+.5,
    miss_count = sum(miss)+.5,
    c_r_count = sum(c_r)+.5,
    .groups = 'drop')%>%
  mutate(
    dprime = dprime(hit_count, 
                             f_a_count, 
                             hit_count + miss_count, 
                             f_a_count + c_r_count)$dprime,
    c = dprime(hit_count, 
                        f_a_count, 
                        hit_count + miss_count, 
                        f_a_count + c_r_count)$c)%>%
  select(participant.private.id, task.name, dprime, c)


battery_agg%>%ggplot(aes(x=factor(task.name),y=dprime,color=factor(task.name),alpha=.4))+
  geom_line(aes(group=factor(participant.private.id)),color="black")+
  geom_violin()+
  geom_boxplot(width=.5)+
  geom_point()+
  theme_minimal()

battery_agg%>%ggplot(aes(x=c,y=dprime,color=factor(task.name)))+
  geom_point()+
  theme_minimal()+
  facet_grid(.~factor(task.name))

battery_agg_wider<-battery_agg%>%
  pivot_wider(names_from = task.name,values_from = c(dprime:c))

battery_agg_wider_simp<-battery_agg_wider
ggpairs(battery_agg_wider_simp%>%select(!participant.private.id))
```

```{r}
digit_tidy<-digit_span%>%
  select(participant.private.id,tree.node.key,task.name,
         target,response,length,correct.,total.correct)%>%
  filter(correct.==1)%>%
  group_by(participant.private.id)%>%
  mutate(length=as.numeric(length))%>%
  summarize(max_working_memory=max(length),
         min_working_memory=min(length),
         mean_working_memory=mean(length),
         max_correct=max(total.correct))

digit_tidy%>%
  ggplot(aes(x=1,y=max_correct,color=factor(max_working_memory)))+
  geom_jitter()

digit_cleaned<-digit_tidy%>%
  ungroup()%>%
  mutate(display_medians = median(max_correct),
         abs_distance = abs(display_medians-mean_working_memory),
         mean_distance = mean(abs_distance),
         upper_mad = display_medians+(mean_distance*mad_standard),
         lower_mad = display_medians-(mean_distance*mad_standard))%>%
  filter(max_correct<upper_mad &max_correct>lower_mad)

digit_cleaned%>%
  ggplot(aes(x=mean_working_memory))+
  geom_histogram()

digit_cleaned%>%
  ggplot(aes(x=1,y=mean_working_memory,color=factor(max_working_memory)))+
  geom_jitter()

removal[nrow(removal) + 1, ] <- c("digit_span_participant", 
                                  nrow(digit_tidy) - nrow(digit_cleaned))

digit_cleaned_simp<-digit_cleaned%>%select(participant.private.id,mean_working_memory)
```

```{r}
lextale_tidy<-lextale%>%
  select(participant.private.id,screen.name,zone.type,reaction.time,correct)%>%
  filter(zone.type=="response_keyboard")%>%
  filter(reaction.time>250)

lextale_tidy%>%ggplot(aes(x=reaction.time))+geom_histogram()

lextale_agg<-lextale_tidy%>%
  group_by(participant.private.id)%>%
  summarize(lextale_score=mean(correct))

lextale_agg_cleaned<-lextale_agg%>%
  ungroup()%>%
  mutate(medians = median(lextale_score),
         abs_distance = abs(medians-lextale_score),
         mean_distance = mean(abs_distance),
         upper_mad = medians+(mean_distance*mad_standard),
         lower_mad = medians-(mean_distance*mad_standard))%>%
  filter(lextale_score<upper_mad &lextale_score>lower_mad)


lextale_agg_cleaned%>%ggplot(aes(x=lextale_score))+
  geom_histogram()


removal[nrow(removal) + 1, ] <- c("lextale_agg_participant", 
                                  nrow(lextale_agg) - nrow(lextale_agg_cleaned))

lextale_agg_cleaned_simp<-lextale_agg_cleaned%>%select(lextale_score,participant.private.id)
```
```{r}

italian_lextale_tidy<-italian_lextale%>%
  select(participant.private.id,screen.name,zone.type,reaction.time,correct)%>%
  filter(zone.type=="response_keyboard")%>%
  filter(reaction.time>250)

italian_lextale_tidy%>%ggplot(aes(x=reaction.time))+geom_histogram()

italian_lextale_agg<-italian_lextale_tidy%>%
  group_by(participant.private.id)%>%
  summarize(italian_lextale_score=mean(correct))

italian_lextale_agg_cleaned<-italian_lextale_agg%>%
  ungroup()%>%
  mutate(medians = median(italian_lextale_score),
         abs_distance = abs(medians-italian_lextale_score),
         mean_distance = mean(abs_distance),
         upper_mad = medians+(mean_distance*mad_standard),
         lower_mad = medians-(mean_distance*mad_standard))%>%
  filter(italian_lextale_score<upper_mad &italian_lextale_score>lower_mad)


italian_lextale_agg_cleaned%>%ggplot(aes(x=italian_lextale_score))+
  geom_histogram()


removal[nrow(removal) + 1, ] <- c("italian_lextale_agg_participant", 
                                  nrow(italian_lextale_agg) - nrow(italian_lextale_agg_cleaned))

italian_lextale_agg_cleaned_simp<-italian_lextale_agg_cleaned%>%select(italian_lextale_score,participant.private.id)
```

```{r}
autism_tidy<-autism%>%
  select(participant.private.id,question.key,response)%>%
  filter(str_detect(question.key, "quantised"))%>%
  mutate(response=as.numeric(response))


agree<-c(1, 2, 4, 5, 6, 7, 9, 12, 13, 16, 18, 19, 20, 21, 
         22, 23, 26, 33, 35, 39, 41,42, 43, 45, 46)
disagree<-c(3, 8, 10, 11, 14, 15, 17, 24, 25, 27, 28, 29, 
            30, 31, 32,34, 36, 37, 38, 40, 44, 47, 48, 49, 50)
agr_key<-c("1","2")
dis_key<-c("3","4")

autism_cleaned<-autism_tidy%>%
  mutate(key_response = str_replace_all(question.key, "AQ", ""))%>%
  mutate(key_response = str_replace_all(key_response, "-quantised", ""))%>%
  mutate(points=case_when(key_response%in%agree & response %in% agr_key~1,
                          key_response%in%agree & response %in% dis_key~0,
                          key_response%in%disagree & response %in% dis_key~1,
                          key_response%in%disagree & response %in% agr_key~0))%>%
  group_by(participant.private.id)%>%
  summarize(autism_score=mean(points))

autism_cleaned%>%ggplot(aes(x=autism_score))+geom_histogram()
```

```{r}
s_exp1_cleaned<-s_exp1%>%
  select(participant.private.id,spreadsheet.row,response,real_1_distractor_0,zone.type,display,audio,
         q1_image,q2_image,q3_image,q4_image,
         id,grouping_id,sorting,audio)%>%
  filter(zone.type=="response_button_image")%>%
  mutate(audio=tolower(audio),
         word_play = str_remove(str_extract(audio, "^[^_]+"), "\\.wav"),
         word_play_start = substr(word_play, 1, 3),
         stress_play = str_remove(str_extract(audio, "(?<=_)[^_]+"), "\\.wav"),
         response_word = str_extract(response, "(?<=\\d)[a-zA-Z]+(?=\\.jpeg)"),
         response_thing = str_extract(response, "(?<=\\D)\\d{2}(?=[a-zA-Z]+\\.jpeg)"),
         correct=if_else(response_word==word_play,1,0))%>%
  mutate(stress_play=if_else(stress_play=="p","Penultimate","Anti-penultimate"),
         q1_word= str_extract(q1_image, "(?<=\\d)[a-zA-Z]+(?=\\.jpeg)"),
         q2_word= str_extract(q2_image, "(?<=\\d)[a-zA-Z]+(?=\\.jpeg)"),
         q3_word= str_extract(q3_image, "(?<=\\d)[a-zA-Z]+(?=\\.jpeg)"),
         q4_word= str_extract(q4_image, "(?<=\\d)[a-zA-Z]+(?=\\.jpeg)"))%>%
 mutate(target_quantile=case_when(q1_word==word_play~1,
                                 q2_word==word_play~2,
                                 q3_word==word_play~3,
                                 q4_word==word_play~4),
       competitor_quantile = case_when(
      q1_word != word_play & str_detect(q1_word,word_play_start) ~ 1,
      q2_word != word_play & str_detect(q2_word,word_play_start) ~ 2,
      q3_word != word_play & str_detect(q3_word,word_play_start) ~ 3,
      q4_word != word_play & str_detect(q4_word,word_play_start) ~ 4))%>%
  rowwise() %>%
  mutate(distractor_1_quantile = {
    possible_values <- setdiff(1:4, c(target_quantile, competitor_quantile))
    sample(possible_values, 1)
  })%>%
  mutate(distractor_2_quantile = 10-sum(distractor_1_quantile,target_quantile,competitor_quantile))%>%
  ungroup()

s_exp1_cleaned<-s_exp1_cleaned%>%
  mutate(target = case_when(target_quantile == 1 ~ q1_word,
                            target_quantile == 2 ~ q2_word,
                            target_quantile == 3 ~ q3_word,
                            target_quantile == 4 ~ q4_word),
         competitor = case_when(competitor_quantile == 1 ~ q1_word,
                                competitor_quantile == 2 ~ q2_word,
                                competitor_quantile == 3 ~ q3_word,
                                competitor_quantile == 4 ~ q4_word),
         dist_1 = case_when(distractor_1_quantile == 1 ~ q1_word,
                                  distractor_1_quantile == 2 ~ q2_word,
                                  distractor_1_quantile == 3 ~ q3_word,
                                  distractor_1_quantile == 4 ~ q4_word),
         dist_2 = case_when(distractor_2_quantile == 1 ~ q1_word,
                                  distractor_2_quantile == 2 ~ q2_word,
                                  distractor_2_quantile == 3 ~ q3_word,
                                  distractor_2_quantile == 4 ~ q4_word))

```

```{r}
item_agg<-s_exp1_cleaned%>%group_by(word_play)%>%
  summarise(score=mean(correct))%>%
  ungroup()%>%
  mutate(medians = median(score),
         abs_distance = abs(medians-score),
         mean_distance = mean(abs_distance),
         upper_mad = medians+(mean_distance*mad_standard),
         lower_mad = medians-(mean_distance*mad_standard))

item_agg%>%
  ggplot(aes(x=factor(word_play),y=score))+
  geom_point()+
  geom_point(aes(x=factor(word_play),y=upper_mad),color="red")+
  geom_point(aes(x=factor(word_play),y=lower_mad),color="red")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))

item_agg_keep<-item_agg%>%
  filter(score<upper_mad & score>lower_mad)

removal[nrow(removal) + 1, ] <- c("exp1_item_removed", 
                                  length(unique(item_agg$word_play)) - length(unique(item_agg_keep$word_play)))

part_agg<-s_exp1_cleaned%>%group_by(participant.private.id)%>%
  summarise(score=mean(correct))%>%
  ungroup()%>%
    mutate(medians = median(score),
           abs_distance = abs(medians-score),
           mean_distance = mean(abs_distance),
           upper_mad = medians+(mean_distance*mad_standard),
           lower_mad = medians-(mean_distance*mad_standard))

part_agg%>%
  ggplot(aes(x=factor(participant.private.id),y=score))+
  geom_point()+
  geom_point(aes(x=factor(participant.private.id),y=upper_mad),color="red")+
  geom_point(aes(x=factor(participant.private.id),y=lower_mad),color="red")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))

part_agg_keep<-part_agg%>%
  filter(score<upper_mad & score>lower_mad)

removal[nrow(removal) + 1, ] <- c("exp1_part_removed", 
                                  length(unique(part_agg$participant.private.id)) - length(unique(part_agg_keep$participant.private.id)))

#s_exp1_cleaned<-s_exp1_cleaned%>%filter(participant.private.id%in%part_agg_keep$participant.private.id)
#s_exp1_cleaned<-s_exp1_cleaned%>%filter(word_play%in%item_agg_keep$word_play)

length(unique(s_exp1_cleaned$participant.private.id))
length(unique(s_exp1_cleaned$word_play))

list_o_word<-c('canapa','candido','celebre','codice','comico','eremo','estero','federa','forbice','fragola','impeto','lattice','loculo','macabro','mastice','missile','monito','panico','protesi','remora','salice','senape','tonaca','zigomo','canale','candito','celeste','codino','comizio','erede','esteta','fedele','forbito','fragore','impero','lattina','locusta','macaco','mastino','missiva','monile','panino','protesta','remoto','saliva','senato','tonale','zigote')

s_exp1_cleaned<-s_exp1_cleaned%>%
  filter(correct==1)%>%
  filter(word_play%in%list_o_word)

prac<-s_exp1_cleaned%>%ungroup()%>%group_by(real_1_distractor_0,stress_play,word_play)%>%count()
```

```{r}
s_exp1_et_cleaned<-s_exp1_et%>%
  select(participant_id,spreadsheet_row,type,time_stamp,
         time_elapsed,x_pred_normalised,y_pred_normalised,face_conf)%>%
  mutate(participant.private.id=participant_id,
         spreadsheet.row=spreadsheet_row)%>%
  select(!c(participant_id,spreadsheet_row))%>%
  filter(type=="prediction")
  
origin<-c(0,0)
s_exp1_data_all <- s_exp1_et_cleaned %>%
  left_join(s_exp1_cleaned)%>%
  na.omit()%>%
  filter(face_conf>.5)%>%
  mutate(x_pred_normalised=x_pred_normalised-.5,
         y_pred_normalised=y_pred_normalised-.5)%>%
  filter(x_pred_normalised<1&x_pred_normalised>-1)%>%
  filter(y_pred_normalised<1&y_pred_normalised>-1)%>%
  mutate(current_quadrant = case_when(
            x_pred_normalised < origin[1] & y_pred_normalised > origin[2] ~ q1_word,
            x_pred_normalised > origin[1] & y_pred_normalised > origin[2] ~ q2_word,
            x_pred_normalised < origin[1] & y_pred_normalised < origin[2] ~ q3_word,
            x_pred_normalised > origin[1] & y_pred_normalised < origin[2] ~ q4_word))%>%
  mutate(target_looks=if_else(current_quadrant==target,1,0),
         competitor_looks=if_else(current_quadrant==competitor,1,0),
         dist1_looks=if_else(current_quadrant==dist_1,1,0),
         dist2_looks=if_else(current_quadrant==dist_2,1,0))%>%
  group_by(participant.private.id,spreadsheet.row,stress_play)%>%
  mutate(time=time_stamp-min(time_stamp),
         time_rounded = round(time / 50) * 50)%>%
  mutate(time_rounded=time_rounded-1000)%>%
  mutate(time_rounded=time_rounded-200)%>%
  filter(time_rounded<1000&time_rounded>=0)


ets_exp1_all_agg<-s_exp1_data_all%>%
  group_by(stress_play,time_rounded)%>%
  summarise(mean_target_looks=mean(target_looks),
            mean_competitor_looks=mean(competitor_looks),
            mean_dist1_looks=mean(dist1_looks),
            mean_dist2_looks=mean(dist2_looks))%>%
  ungroup()%>%
  pivot_longer(cols=c(mean_target_looks:mean_dist2_looks),names_to = "names",values_to="values")
  

penn_times<-c(300, 500, 650)
anti_times<-c(390, 530, 625)

df_1 <- data.frame(
  time_rounded = penn_times,
  values = 0.6,
  labels = c("ca", "LA", "ta")
)

df_2 <- data.frame(
  time_rounded = anti_times,
  values = 0.6,
  labels = c("CA", "la", "mo")
)

plot1<-ets_exp1_all_agg %>%
  filter(stress_play == "Penultimate") %>%
  ggplot(aes()) +
  geom_text(data=df_1,aes(label=labels,x = time_rounded, y = values),
            family = "Arial", size = 4, fontface = "bold")+
  geom_point(aes(x = time_rounded, y = values, color = names)) +
  geom_smooth(aes(x = time_rounded, y = values, color = names),se=FALSE)+
  scale_y_continuous(breaks=seq(0, 1, by = .25),
                     labels=seq(0, 1, by = .25))+
  scale_x_continuous(
    breaks = seq(min(ets_exp1_all_agg$time_rounded, na.rm = TRUE), 
                 max(ets_exp1_all_agg$time_rounded, na.rm = TRUE), by = 200),
    labels = seq(min(ets_exp1_all_agg$time_rounded, na.rm = TRUE), 
                 max(ets_exp1_all_agg$time_rounded, na.rm = TRUE), by = 200),
    minor_breaks = c(0,200,201, 396, 566, 699,800), 
    position = "bottom")+
  theme_minimal() +
  theme(
    axis.text.x.top = element_text(color = "black"),
    axis.text.x = element_text(color = "black"),
    panel.grid.major.x = element_line(color = "grey", size = 0.1),
    panel.grid.minor.x = element_line(linetype = "dotted", color = "black", size = 0.5),
    panel.grid.minor.y = element_blank(),
    panel.grid.major.y = element_line(color = "grey", size = 0.1),
    legend.position = c(0.1, 0.9),
    legend.justification = c(0, 1),
    legend.background = element_rect(fill = "white", colour = "black"))+
  labs(x = NULL,y= "") +
  guides(color = guide_legend(title = "Looks to:"))+
  scale_color_manual(
    values = c("mean_target_looks" = "#c41230", "mean_competitor_looks" = "#007bc0", 
               "mean_dist1_looks" = "#A7A7A9", "mean_dist2_looks" = "#000000"),
    labels = c("Competitor", "Distractor", "Distractor","Target")
  )

plot2<-ets_exp1_all_agg %>%
  filter(stress_play == "Anti-penultimate") %>%
  ggplot(aes()) +
  geom_text(data=df_2,aes(label=labels,x = time_rounded, y = values),
            family = "Arial", size = 4, fontface = "bold")+
  geom_point(aes(x = time_rounded, y = values, color = names)) +
  geom_smooth(aes(x = time_rounded, y = values, color = names),se=FALSE)+
  scale_y_continuous(breaks=seq(0, 1, by = .25),
                     labels=seq(0, 1, by = .25))+
  scale_x_continuous(
    breaks = seq(min(ets_exp1_all_agg$time_rounded, na.rm = TRUE), 
                 max(ets_exp1_all_agg$time_rounded, na.rm = TRUE), by = 200),
    labels = seq(min(ets_exp1_all_agg$time_rounded, na.rm = TRUE), 
                 max(ets_exp1_all_agg$time_rounded, na.rm = TRUE), by = 200),
    minor_breaks = c(0,200,201, 499, 566, 669,800),
    position = "bottom")+
  theme_minimal() +
  theme(
    axis.text.x.top = element_text(color = "black"),
    axis.text.x = element_blank(),
    panel.grid.major.x = element_line(color = "grey", size = 0.1),
    panel.grid.minor.x = element_line(linetype = "dotted", color = "black", size = 0.5),
    panel.grid.minor.y = element_blank(),
    panel.grid.major.y = element_line(color = "grey", size = 0.1),
    #legend.position = "none",
    legend.justification = c(0, 1),
    legend.background = element_rect(fill = "white", colour = "black"))+
  labs(x = NULL,y= "") +
  guides(color = guide_legend(title = "Looks to:"))+
  scale_color_manual(
    values = c("mean_target_looks" = "#c41230", "mean_competitor_looks" = "#007bc0", 
               "mean_dist1_looks" = "#A7A7A9", "mean_dist2_looks" = "#000000"),
    labels = c("Competitor", "Distractor", "Distractor","Target")
  )

combined_plot <- plot_grid(plot1, plot2, ncol = 1)+
  draw_label("Anti-penultimate (bottom) and penultimate (top) items proportion of looks", x = 0.02, y = 0.5, angle = 90, size = 14)
combined_plot

#ggsave("../visuals/pen_vs_anti_pen.jpeg", plot = combined_plot, width = 6, height = 8, dpi = 300)
```


```{r}

penn_times<-c(396, 566,699)
anti_times<-c(499, 566,669)

comp_targ<-s_exp1_data_all%>%
  ungroup()%>%
  filter(time_rounded<699)%>%
  mutate(syllable=case_when(time_rounded<200~0,
                            stress_play=="Penultimate" & time_rounded>200 &
                              time_rounded<penn_times[1]~1,
                            stress_play=="Penultimate" & time_rounded>=penn_times[1] &
                              time_rounded<mean(penn_times[2],penn_times[3]) ~2,
                            stress_play=="Penultimate" & time_rounded<=penn_times[3]~3,
                            stress_play=="Anti-penultimate" & time_rounded>200 &
                              time_rounded<anti_times[1]~1,
                            stress_play=="Anti-penultimate" & time_rounded>=anti_times[1] &
                              time_rounded<mean(anti_times[2],anti_times[3]) ~2,
                            stress_play=="Anti-penultimate" & time_rounded<=anti_times[3]~3))

comp_tar_longer<-comp_targ%>%
  pivot_longer(cols=c(target_looks:dist2_looks),names_to = "names",values_to="values")%>%
  mutate(syllable=as.factor(syllable),
         stress_play=as.factor(stress_play))


contrasts(comp_tar_longer$stress_play)<-c(.5,-.5)
contrasts(comp_tar_longer$stress_play)
comp_tar_longer$names<-as.factor(comp_tar_longer$names)
contrasts(comp_tar_longer$names)
#data$looks <- factor(data$looks, levels = c("dist1_looks", "dist2_looks", "target_looks", "competitor_looks"))


contrasts(factor(comp_tar_longer$names))
contrasts(comp_tar_longer$stress_play)
levels(comp_tar_longer$stress_play)<-c("Anti-penultimate","Penultimate")
levels(comp_tar_longer$stress_play)
comp_tar_model<-glm(values~names*stress_play*syllable,data=comp_tar_longer,family = "binomial")
comp_tar_model1<-glm(values~stress_play*names+syllable,data=comp_tar_longer,family = "binomial")
comp_tar_model2<-glm(values~stress_play+names*syllable,data=comp_tar_longer,family = "binomial")
comp_tar_model3<-glm(values~stress_play+names+syllable,data=comp_tar_longer,family = "binomial")
summary(comp_tar_model)
summary(comp_tar_model1)
summary(comp_tar_model2)
summary(comp_tar_model3)

anova(comp_tar_model,comp_tar_model1)
anova(comp_tar_model1,comp_tar_model2)
anova(comp_tar_model2,comp_tar_model3)

bic_model = BIC(comp_tar_model)
bic_model1 = BIC(comp_tar_model1)
bic_model2 = BIC(comp_tar_model2)
bic_model3 = BIC(comp_tar_model3)

bic_model
bic_model1
bic_model2
bic_model3
```
```{r}
library(broom)
tidy_model <- tidy(comp_tar_model2, effects = "fixed")%>%
  mutate(
    main = case_when(
      str_detect(term, ":") ~ 1,
      TRUE ~ 0))%>%
   mutate(
    looks = case_when(
      str_detect(term, "target") ~ "target",
      str_detect(term, "dist1") ~ "distractor_1",
      str_detect(term, "dist2") ~ "distractor_2",
      TRUE ~ "Base_looks"))%>%
  mutate(
    syllable = case_when(
      str_detect(term, "syllable1") ~ "1",
      str_detect(term, "syllable2") ~ "2",
      str_detect(term, "syllable3") ~ "3",
      TRUE ~ "0"))%>%
  mutate(
      term=str_replace(term, "syllable1","Syllable 1"),
      term=str_replace(term, "syllable2","Syllable 1.5"),
      term=str_replace(term, "syllable3","Syllable 2"),
      term=str_replace(term, "_looks",""),
      term=str_replace(term, "names","Looks "),
      term=str_replace(term, "stress_play","Stress"),
      term=str_replace(term, "Stress1","Stress Anti"))%>%
  arrange(main, syllable, looks) %>%
  mutate(
    row_number = row_number(),
    looks = as.factor(looks),
    Significance = case_when(
      p.value < 0.001 ~ "***",
      p.value < 0.01 ~ "**",
      p.value < 0.05 ~ "*",
      TRUE ~ ""))


colors <- c("Base_looks" = "#007bc0", "distractor_1" = "#A7A7A9", 
            "distractor_2" = "#000000", "target" = "#c41230")

pen_anti_model<-ggplot(tidy_model, aes(x = estimate, y = row_number,color=factor(looks))) +
  geom_point() +
  geom_errorbarh(aes(xmin = estimate - 1.96 * std.error, xmax = estimate + 1.96 * std.error), height = 0) +
  labs(title = , x = "Estimated Coefficients", y = "",color = "Looks to grouping") +
  theme_minimal()+
  geom_vline(xintercept = 0,color = "#007bc0")+
  scale_y_continuous(breaks = tidy_model$row_number, labels = tidy_model$term)+
  scale_color_manual(
    values = c( "Base_looks" = "#007bc0", "distractor_1" = "#A7A7A9", 
                "distractor_2" = "#000000","target" = "#c41230"),
    labels = c( "Base", "Distractor 1", "Distractor 2","Target")
  )+
  annotate("rect", xmin = -2.7, xmax = -1.45, ymin = -1.5, ymax = 17.5, fill = "white",color="grey") +
  geom_text(aes(y = row_number,x=-1.5, label = term, color = factor(looks)),hjust = 1, size = 4,angle=40,show.legend = FALSE)+
  xlim(-2.7, 1)+
  coord_flip()+
  theme(axis.text.y = element_text(angle = 15, hjust = 1),
        axis.text.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.minor.y = element_blank(),
        axis.title.y = element_text(hjust = .75, vjust = 0.0),
        axis.title.x = element_text(hjust = .0, vjust = 0),
        panel.border = element_blank(),
        legend.position = "bottom")+
  scale_x_continuous(breaks=seq(-1, 1, by = .5))+
  geom_text(aes(y = 1,x=-2.5, label = "Terms"),color = "black",hjust = 1, size = 5,angle=0,show.legend = FALSE)+
    geom_text(aes(y = row_number, x = -1.2, label = Significance), hjust = 0, vjust = .5,angle=90, color = "black", show.legend = FALSE)

pen_anti_model
#ggsave("../visuals/pen_vs_anti_pen_model.jpeg", plot = pen_anti_model, width = 10, height = 6.6, dpi = 300)
```


```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library(conflicted)
ets_exp1_all_agg_part_wider<-comp_tar_longer%>%
  pivot_wider(names_from = names,values_from = values)%>%
  filter(syllable!=3)%>%
  group_by(participant.private.id,stress_play,syllable)%>%
  summarise(mean_target_looks=mean(target_looks),
            mean_competitor_looks=mean(competitor_looks),
            mean_dist1_looks=mean(dist1_looks),
            mean_dist2_looks=mean(dist2_looks))%>%
  mutate(proportion_o_looks=mean_target_looks-mean_competitor_looks)%>%
  left_join(battery_agg_wider_simp)%>%
  left_join(digit_cleaned_simp)%>%
  left_join(lextale_agg_cleaned_simp)%>%
  left_join(italian_lextale_agg_cleaned_simp)%>%
  left_join(autism_cleaned)

#write.csv(ets_exp1_all_agg_part_wider, "../../ppcc_iflu_data/ets_exp1_all_agg_part_wider.csv")
```

##competitor analysis
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library(conflicted)
ets_exp1_all_agg_part_wider<-read.csv("../../ppcc_iflu_data/ets_exp1_all_agg_part_wider.csv")

ets_exp1_all_agg_part_wider%>%
  ggplot(aes(x=stress_play,y=proportion_o_looks,color=stress_play))+
  geom_boxplot()+
  geom_jitter()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))+
  facet_wrap(.~syllable)

ets_exp1_all_agg_part_wider$stress_play<-as.factor(ets_exp1_all_agg_part_wider$stress_play)
contrasts(ets_exp1_all_agg_part_wider$stress_play)
contrasts(ets_exp1_all_agg_part_wider$stress_play)<-c(-.5,.5)

full_data_exp1<-ets_exp1_all_agg_part_wider%>%select(!c(participant.private.id,c_battery_up_dur:c_battery_up_risetime,mean_target_looks:mean_dist2_looks))
#ggpairs(full_data_exp1)

full_data_exp1$stress_play<-as.factor(full_data_exp1$stress_play)
contrasts(full_data_exp1$stress_play)
contrasts(full_data_exp1$stress_play)<-c(.5,-.5)
contrasts(full_data_exp1$stress_play)

full_data_exp1 <- full_data_exp1 %>%
  select(-X) %>%
  select(proportion_o_looks, everything()) %>%
  mutate(across(dprime_battery_up_dur:autism_score, ~ scale(.)[, 1]))
```

```{r}
#installed.packages("leaps")
#installed.packages("MASS")
#installed.packages("caret")
#library(MASS) 
#library(caret)
#library(leaps)

# Ensure 'stress_play' is always included in the model
force_var <- "stress_play"
ncol(full_data_exp1)
force_in_vector <- rep(FALSE,ncol(full_data_exp1))  # Assuming 28 variables as in your output
names(force_in_vector) <- colnames(full_data_exp1)  # Make sure this matches your data structure
names(force_in_vector)
force_in_vector["stress_play"] <- TRUE
force_in_vector
# Exclude the response and the forced variable from the predictors
predictors <- setdiff(names(full_data_exp1), c("proportion_o_looks", force_var))
predictors
# Create the formula ensuring 'stress_play' is always included
formula_interactions <- as.formula(paste("proportion_o_looks ~ (", force_var, "+", paste(predictors, collapse = "+"), ")^2"))
formula_interactions

subset_fit <- leaps::regsubsets(formula_interactions, data = full_data_exp1, nbest = 1, nvmax = 15, force.in = force_in_vector,really.big=T)

# Perform subset selection allowing other variables to vary
subset_summary <- summary(subset_fit)
subset_summary

# Print summary statistics
subset_summary$adjr2
subset_summary$cp
subset_summary$bic

# Choose a model based on BIC
selected_model <- which.min(subset_summary$bic)
subset_summary$which[selected_model, ]

m1<-lm(proportion_o_looks~(.)^2,data=full_data_exp1)
summary(m1)

included_predictors <- names(subset_summary$which[selected_model, ][subset_summary$which[selected_model, ] & names(subset_summary$which[selected_model, ]) != "(Intercept)"])

formula_str <- "proportion_o_looks ~"
formula_str <- paste(formula_str, paste(included_predictors, collapse = " + "), sep = "")
formula_str

formula_str <- gsub("Anti-penultimate", "", formula_str, perl = TRUE)
formula_str <- gsub("1", "", formula_str, perl = TRUE)
model_formula <- as.formula(formula_str)

model_lm <- lm(model_formula, data = ets_exp1_all_agg_part_wider)
model_lm
# Display the summary of the model
summary(model_lm)
check_model(m1)
check_model(model_lm)
```

```{r message=FALSE, warning=FALSE, paged.print=FALSE}

coef_df <- summary(model_lm)$coefficients

coef_df <- as.data.frame(coef_df)
coef_df$Predictor <- rownames(coef_df)
rownames(coef_df) <- NULL

ci_level <- 1.96
coef_df$CI_Lower <- coef_df$Estimate - ci_level * coef_df$`Std. Error`
coef_df$CI_Upper <- coef_df$Estimate + ci_level * coef_df$`Std. Error`

ggplot(coef_df, aes(x = Predictor, y = Estimate, ymin = CI_Lower, ymax = CI_Upper)) +
  geom_pointrange() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(title = "Effect Sizes and Confidence Intervals for Model Coefficients",
       x = "Predictors",
       y = "Estimate") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+coord_flip()+theme_bw()
```
#target analysis

```{r message=FALSE, warning=FALSE, paged.print=FALSE}

ets_exp1_all_agg_part_wider$stress_play<-as.factor(ets_exp1_all_agg_part_wider$stress_play)
contrasts(ets_exp1_all_agg_part_wider$stress_play)
contrasts(ets_exp1_all_agg_part_wider$stress_play)<-c(-.5,.5)

full_data_exp2<-ets_exp1_all_agg_part_wider%>%
  select(!c(participant.private.id,c_battery_up_dur:c_battery_up_risetime,mean_competitor_looks:mean_dist2_looks,proportion_o_looks))%>%
  na.omit()%>%
  select(-X)


ggpairs(full_data_exp1)
full_data_exp2$stress_play<-as.factor(full_data_exp2$stress_play)
contrasts(full_data_exp2$stress_play)
contrasts(full_data_exp2$stress_play)<-c(-.5,.5)
contrasts(full_data_exp2$stress_play)

full_data_exp2 <- full_data_exp2 %>%
  select(mean_target_looks, everything())%>%
  ungroup()%>%
  mutate(across(dprime_battery_up_dur:autism_score, ~ scale(.)[, 1]))
```

```{r}
#installed.packages("leaps")
#installed.packages("MASS")
#installed.packages("caret")
#library(MASS) 
#library(caret)
#library(leaps)

# Ensure 'stress_play' is always included in the model
force_var2 <- "stress_play"
ncol(full_data_exp2)
force_in_vector2 <- rep(FALSE,ncol(full_data_exp2))  # Assuming 28 variables as in your output
names(force_in_vector2) <- colnames(full_data_exp2)  # Make sure this matches your data structure
names(force_in_vector2)
force_in_vector2["stress_play"] <- TRUE
force_in_vector2
# Exclude the response and the forced variable from the predictors
predictors2 <- setdiff(names(full_data_exp2), c("mean_target_looks", force_var2))
predictors2
# Create the formula ensuring 'stress_play' is always included
formula_interactions2 <- as.formula(paste("mean_target_looks ~ (", force_var2, "+", paste(predictors2, collapse = "+"), ")^2"))
formula_interactions2

subset_fit2 <- leaps::regsubsets(formula_interactions2, data = full_data_exp2, nbest = 1, nvmax = 15, force.in = force_in_vector2,really.big=T)

# Perform subset selection allowing other variables to vary
subset_summary2 <- summary(subset_fit2)
subset_summary2

# Print summary statistics
subset_summary2$adjr2
subset_summary2$cp
subset_summary2$bic

# Choose a model based on BIC
selected_model2 <- which.min(subset_summary2$bic)
subset_summary2$which[selected_model2, ]

m1.2<-lm(mean_target_looks~(.)^2,data=full_data_exp2)
summary(m1.2)

included_predictors2 <- names(subset_summary2$which[selected_model2, ][subset_summary2$which[selected_model2, ] & names(subset_summary2$which[selected_model2, ]) != "(Intercept)"])

formula_str2 <- "mean_target_looks ~"
formula_str2 <- paste(formula_str2, paste(included_predictors2, collapse = " + "), sep = "")
formula_str2

formula_str2 <- gsub("Anti-penultimate", "", formula_str2, perl = TRUE)
formula_str2 <- gsub("1", "", formula_str2, perl = TRUE)
formula_str2 <- gsub("2", "", formula_str2, perl = TRUE)
model_formula2 <- as.formula(formula_str2)
model_formula2

model_lm2 <- lm(model_formula2, data = ets_exp1_all_agg_part_wider)
model_lm2
# Display the summary of the model
summary(model_lm2)
check_model(m1.2)
check_model(model_lm2)
```


```{r}
coef_df2 <- summary(model_lm2)$coefficients
summary(model_lm2)
coef_df2 <- as.data.frame(coef_df2)
coef_df2$Predictor <- rownames(coef_df2)
rownames(coef_df2) <- NULL

ci_level <- 1.96
coef_df2$CI_Lower <- coef_df2$Estimate - ci_level * coef_df2$`Std. Error`
coef_df2$CI_Upper <- coef_df2$Estimate + ci_level * coef_df2$`Std. Error`

ggplot(coef_df2, aes(x = Predictor, y = Estimate, ymin = CI_Lower, ymax = CI_Upper)) +
  geom_pointrange() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(title = "Effect Sizes and Confidence Intervals for Model Coefficients",
       x = "Terms",
       y = "Estimate") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+coord_flip()+theme_bw()

coef_df$model<-"competition"
coef_df2$model<-"target looks"
```
#combined plots for target looks and competition looks
```{r}
combined_df <- bind_rows(coef_df, coef_df2)%>%
  mutate(Significance = case_when(
      `Pr(>|t|)` < 0.001 ~ "***",
      `Pr(>|t|)` < 0.01 ~ "**",
      `Pr(>|t|)` < 0.05 ~ "*",
      TRUE ~ ""))

combined_df<-combined_df%>%
mutate(Predictor = str_replace_all(Predictor, "battery_up_", ""))%>%
  mutate(Predictor = str_replace_all(Predictor, "_", " "))%>%
  mutate(Predictor = str_replace_all(Predictor, "score", ""))%>%
  mutate(Predictor = str_replace_all(Predictor, "score", ""))%>%
  mutate(Predictor = str_replace_all(Predictor, "mean", ""))%>%
  mutate(Predictor = str_replace_all(Predictor, "stress play", "Stress "))%>%
  mutate(Predictor = str_replace_all(Predictor, "dprime dur", "Duration d'"))%>%
  mutate(Predictor = str_replace_all(Predictor, "dprime formants", "Formants d'"))%>%
  mutate(Predictor = str_replace_all(Predictor, "dprime ptich", "Pitch d'"))%>%
  mutate(Predictor = str_replace_all(Predictor, "dprime risetime", "Risetime d'"))%>%
  mutate(Predictor = str_replace_all(Predictor, "working memory", "Working Memory"))%>%
  mutate(Predictor = str_replace_all(Predictor, "syllable", "Syllable"))%>%
  mutate(Predictor = str_replace_all(Predictor, "autism", "Autism"))%>%
  mutate(Predictor = str_replace_all(Predictor, "lextale", "Lextale English"))%>%
  mutate(Predictor = as.factor(Predictor))


combined_df$Predictor <- factor(
  combined_df$Predictor, 
  levels = c("(Intercept)", "Syllable", "Pitch d'", "Syllable: Working Memory",           
             "Stress Anti-penultimate:Formants d'","Stress Penultimate:Formants d'",
             " Working Memory:Pitch d'"," Working Memory:Risetime d'",
             "Pitch d':Autism ","Pitch d':Lextale English ",
             "Duration d':Lextale English ","Formants d':Pitch d'" ))

# Plot
target_vs_compet<-combined_df%>%ggplot(aes(x = Predictor, y = Estimate, ymin = CI_Lower, ymax = CI_Upper, color = model)) +
  theme_minimal()+
  geom_hline(yintercept = 0,color="black",alpha=.5)+
  geom_pointrange(position = position_dodge(width = 0.5),alpha=.7) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position="bottom") +
  labs(x = "Terms", y = "Estimated Coefficients") +
  scale_color_manual(values = c("competition" = "#624670", "target looks" = "#C41230"))+
  geom_text(aes(x = Predictor, y = -1.2, label = Significance,color=model), 
            show.legend = FALSE,size=5,fontface = "bold")+
  coord_flip()
  
target_vs_compet
#ggsave("../visuals/target_vs_compet.jpeg", plot = target_vs_compet, width = 10, height = 7, dpi = 300)

```

#raw data participants
```{r}
library(conflicted)
full_data_exp2.2<-ets_exp1_all_agg_part_wider%>%
  select(!c(c_battery_up_dur:c_battery_up_risetime,mean_competitor_looks:mean_dist2_looks))%>%
  na.omit()%>%
  select(-X)

full_data_exp2_longer<-full_data_exp2.2%>%
  select(mean_target_looks, everything())%>%
  mutate(across(c(mean_target_looks, dprime_battery_up_dur:autism_score), ~ scale(.x)[, 1])) %>%
  pivot_longer(
    cols = c(mean_target_looks, dprime_battery_up_dur:autism_score),
    names_to = "names",
    values_to = "values")%>%
  filter(values<=6)

full_data_exp2_longer%>%ggplot(aes(x=names,y=values,color=factor(participant.private.id),alpha=.2))+
  geom_point()+
  geom_line(aes(group=participant.private.id))+
  facet_grid(stress_play~syllable)+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

library(ggridges)
full_data_exp2_longer%>%
  ggplot(aes(x = values, y = names, fill = stat(x))) +
  geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01) +
  scale_fill_viridis_c(name = "Temp. [F]", option = "C") +
  labs(title = 'Temperatures in Lincoln NE in 2016')
  

full_data_exp2_longer_names<-full_data_exp2_longer%>%
  filter(names!="mean_target_looks")%>%
  mutate(names = str_replace_all(names, "battery_up_", ""))%>%
  mutate(names = str_replace_all(names, "_", " "))%>%
  mutate(names = str_replace_all(names, "score", ""))%>%
  mutate(names = str_replace_all(names, "score", ""))%>%
  mutate(names = str_replace_all(names, "mean", ""))%>%
  mutate(names = str_replace_all(names, "dprime dur", "Duration d'"))%>%
  mutate(names = str_replace_all(names, "dprime formants", "Formants d'"))%>%
  mutate(names = str_replace_all(names, "dprime ptich", "Pitch d'"))%>%
  mutate(names = str_replace_all(names, "dprime risetime", "Risetime d'"))%>%
  mutate(names = str_replace_all(names, "lextale", "Lextale English"))%>%
  mutate(names = str_replace_all(names, "italian Lextale English", "Lextale Italian"))%>%
  mutate(names = str_replace_all(names, "working memory", "Working Memory"))%>%
  mutate(names = str_replace_all(names, "autism", "Autism Questionnaire"))%>%
  mutate(names = str_replace_all(names, " W", "W"))%>%
  mutate(names = str_replace_all(names, "an ", "an"))%>%
  mutate(names = str_replace_all(names, "re ", "re"))%>%
  mutate(names = str_replace_all(names, "ish ", "ish"))%>%
  mutate(names=as.factor(names))

  
full_data_exp2_longer_names$names <- factor(
  full_data_exp2_longer_names$names, 
  levels = c("Formants d'", "Duration d'", "Pitch d'","Risetime d'","Lextale Italian","Lextale English","Working Memory","Autism Questionnaire"))
  
library(gghalves)

levels(full_data_exp2_longer_names$names)
plot_raw_task<-full_data_exp2_longer_names%>%
  ggplot(aes(y = values, x = names)) + 
  geom_point(
    shape = 95,
    size = 5,
    alpha = .1,
    color = "#009647"
  ) +
  geom_half_violin(alpha=0)+
  geom_half_boxplot(alpha=0,side="r")+
  theme_minimal()+
  scale_x_discrete(position = "top")+
  labs(x="Task names")+
  theme(panel.grid.minor.y=element_blank(),
        panel.grid.major.x = element_line(size = 0.2))

plot_raw_task
#ggsave("../visuals/plot_raw_task.jpeg", plot = plot_raw_task, width = 10, height = 6.6, dpi = 300)

```

########acoustics

```{r}
acoustic_data<-read.csv("acoustic_data_ppcc.csv")

View(acoustic_data)


```

######experiment 2#########
######experiment 2#########
######experiment 2#########

#ET clean up

```{r}
View(s_exp2_cleaned)
s_exp2_cleaned<-s_exp2%>%
  select(participant.private.id,spreadsheet.row,randomise_trials,display,
         randomise_trials,response,reaction.time,zone.type,display,q1,q2,q3,q4,
         target,competitor,distractor,distractor_1,audio)%>%
  filter(zone.type=="response_button_image")
  #filter(display=="test_3_5")%>%
  mutate(
    split_parts = str_split(audio, "_"),
    word_audio = sapply(split_parts, function(x) x[2]),
    stress_audio = sapply(split_parts, function(x) x[3]),
    audio_word_stress=paste(word_audio,stress_audio,sep="_")
  )%>%
  select(-split_parts)%>%
  mutate(
    split_parts = str_split(response, "_"),
    word_response = sapply(split_parts, function(x) x[2]),
    stress_response = sapply(split_parts, function(x) x[3]),
    response_word_stress=paste(word_response,stress_response,sep="_")
  ) %>%
  select(-split_parts)%>%
  mutate(correct=if_else(response_word_stress==audio_word_stress,1,0))%>%
  mutate(randomise_trials=if_else(randomise_trials<=5,5,randomise_trials))%>%
  mutate(stress_response=case_when(stress_response==1~"antipenultimate",
                                   stress_response==2~"penultimate"),
         stress_audio=case_when(stress_audio==1~"antipenultimate",
                                   stress_audio==2~"penultimate"))

s_exp2_part<-s_exp2_cleaned%>%
  #filter(reaction.time<5000&reaction.time>1000)%>%
  filter(participant.private.id%in%s_exp2_cleaned$participant.private.id)

s_exp2_part%>%
  ggplot(aes(x=factor(participant.private.id),y=reaction.time,alpha=.5))+
  geom_jitter()

s_exp2_part<-s_exp2_part%>%
  group_by(participant.private.id)%>%
  mutate(log_rt=sqrt(reaction.time),
         participant_medians = median(log_rt))%>%
  ungroup()%>%
  mutate(medians_rt = median(log_rt),
         abs_distance = abs(log_rt-medians_rt),
         mean_distance = mean(abs_distance),
         upper_mad = medians_rt+(mean_distance*mad_standard),
         lower_mad = medians_rt-(mean_distance*mad_standard))%>%
  dplyr::filter(log_rt<upper_mad &log_rt>lower_mad)%>%
  dplyr::filter(participant_medians<upper_mad &participant_medians>lower_mad)

s_exp2_part%>%
  ggplot(aes(x=factor(participant.private.id),y=log_rt,alpha=.5))+
  geom_jitter()+
  geom_point(aes(x=factor(participant.private.id),y=participant_medians,alpha=.5),color="blue")+
  geom_point(aes(x=factor(participant.private.id),y=lower_mad,alpha=.5),color="red")+
  geom_point(aes(x=factor(participant.private.id),y=upper_mad,alpha=.5),color="red")
    
```


```{r}
s_exp2_agg<-s_exp2_cleaned%>%
  group_by(participant.private.id,randomise_trials,stress_audio)%>%
  summarize(score=mean(correct))

s_exp2_agg%>%ggplot(aes(x=factor(randomise_trials),y=score,color=factor(stress_audio),group=interaction(participant.private.id,factor(stress_audio))))+
  geom_line()+
  geom_point(position = "identity")+
  facet_wrap(factor(stress_audio)~.)
 
s_exp2_agg2<-s_exp2_cleaned%>%
  group_by(participant.private.id,randomise_trials)%>%
  summarize(score=mean(correct))

s_exp2_agg_means<-s_exp2_agg2%>%
  ungroup()%>%
  group_by(randomise_trials)%>%
  summarize(mean=mean(score),
            sd=sd(score))

s_exp2_agg2%>%ggplot(aes(x=factor(randomise_trials),y=score,color=factor(randomise_trials)))+
  geom_boxplot()+
  geom_jitter()+
  stat_summary(fun = mean, geom = "point", shape = 20, size = 3, color = "black") +  # Add mean points
  labs(x = "Randomise Trials", y = "Score", color = "Trial Number") +  # Label the axes and legend
  theme_minimal()
  
```

```{r}
###play
s_exp2_cleaned$dis
play_dat<-s_exp2_cleaned%>%
  filter(randomise_trials==13)%>%
  mutate(target_q1=if_else(target==q1,1,0),
         target_q2=if_else(target==q2,1,0),
         target_q3=if_else(target==q3,1,0),
         target_q4=if_else(target==q4,1,0),
         comp_q1=if_else(competitor==q1,1,0),
         comp_q2=if_else(competitor==q2,1,0),
         comp_q3=if_else(competitor==q3,1,0),
         comp_q4=if_else(competitor==q4,1,0),
         dist1_q1=if_else(distractor==q1,1,0),
         dist1_q2=if_else(distractor==q2,1,0),
         dist1_q3=if_else(distractor==q3,1,0),
         dist1_q4=if_else(distractor==q4,1,0),
         dist2_q1=if_else(distractor_1==q1,1,0),
         dist2_q2=if_else(distractor_1==q2,1,0),
         dist2_q3=if_else(distractor_1==q3,1,0),
         dist2_q4=if_else(distractor_1==q4,1,0))%>%
  summarize(target_q1_total=sum(target_q1),
            target_q2_total=sum(target_q2),
            target_q3_total=sum(target_q3),
            target_q4_total=sum(target_q4),
            comp_q1_total=sum(comp_q1),
            comp_q2_total=sum(comp_q2),
            comp_q3_total=sum(comp_q3),
            comp_q4_total=sum(comp_q4),
            dist1_q1_total=sum(dist1_q1),
            dist1_q2_total=sum(dist1_q2),
            dist1_q3_total=sum(dist1_q3),
            dist1_q4_total=sum(dist1_q4),
            dist2_q1_total=sum(dist2_q1),
            dist2_q2_total=sum(dist2_q2),
            dist2_q3_total=sum(dist2_q3),
            dist2_q4_total=sum(dist2_q4))

play_dat<-s_exp2_cleaned%>%
  filter(randomise_trials==7|randomise_trials==11)%>%
  mutate(target_q1=if_else(target==q1,1,0),
         target_q2=if_else(target==q2,1,0),
         target_q3=if_else(target==q3,1,0),
         target_q4=if_else(target==q4,1,0),
         comp_q1=if_else(competitor==q1,1,0),
         comp_q2=if_else(competitor==q2,1,0),
         comp_q3=if_else(competitor==q3,1,0),
         comp_q4=if_else(competitor==q4,1,0))%>%
  group_by(randomise_trials)%>%
  summarize(target_q1_total=sum(target_q1),
            target_q2_total=sum(target_q2),
            target_q3_total=sum(target_q3),
            target_q4_total=sum(target_q4),
            comp_q1_total=sum(comp_q1),
            comp_q2_total=sum(comp_q2),
            comp_q3_total=sum(comp_q3),
            comp_q4_total=sum(comp_q4))
```


```{r}
library(conflicted)
s_exp2_et_cleaned<-s_exp2_et%>%
  select(participant_id,spreadsheet_row,type,time_stamp,
         time_elapsed,x_pred_normalised,y_pred_normalised,face_conf,screen_index)%>%
  mutate(participant.private.id=participant_id,
         spreadsheet.row=spreadsheet_row)%>%
  select(!c(participant_id,spreadsheet_row))%>%
  filter(type=="prediction")%>%
  group_by(participant.private.id,spreadsheet.row)%>%
  mutate(time=time_stamp-min(time_stamp),
         time_rounded = round(time / 50) * 50)%>%
  mutate(time_rounded=time_rounded-800)%>%
  mutate(time_rounded=time_rounded-200)%>%
  ungroup()

penn_times<-c(396, 566,699)
anti_times<-c(499, 566,669)
s_exp2_data_all<-s_exp2_et_cleaned%>%
  full_join(s_exp2_cleaned_corr)%>%
  na.omit()%>%
  filter(face_conf>.5)%>%
  filter(x_pred_normalised<1&x_pred_normalised>-1)%>%
  filter(y_pred_normalised<1&y_pred_normalised>-1)%>%
  group_by(spreadsheet.row,participant.private.id)%>%
  mutate(randomizer_x = sample(c(1, -1), size = 1, replace = TRUE),
         randomizer_y = sample(c(1, -1), size = 1, replace = TRUE))%>%
  ungroup()%>%
  mutate(x_pred_normalised=x_pred_normalised-.5,
         y_pred_normalised=y_pred_normalised-.5)%>%
  mutate(quadrant = case_when(
            x_pred_normalised < origin[1] & y_pred_normalised > origin[2] ~ 1,
            x_pred_normalised > origin[1] & y_pred_normalised > origin[2] ~ 2,
            x_pred_normalised < origin[1] & y_pred_normalised < origin[2] ~ 3,
            x_pred_normalised > origin[1] & y_pred_normalised < origin[2] ~ 4))%>%
    mutate(random_x_pred_normalised=x_pred_normalised*randomizer_x,
         random_y_pred_normalised=y_pred_normalised*randomizer_y)%>%
    mutate(randomized_quadrant = case_when(
            random_x_pred_normalised < origin[1] & random_y_pred_normalised > origin[2] ~ 1,
            random_x_pred_normalised > origin[1] & random_y_pred_normalised > origin[2] ~ 2,
            random_x_pred_normalised < origin[1] & random_y_pred_normalised < origin[2] ~ 3,
            random_x_pred_normalised > origin[1] & random_y_pred_normalised < origin[2] ~ 4))%>%
  mutate(random_q1=case_when(randomizer_x==1&randomizer_y==1~q1,
                             randomizer_x==1&randomizer_y==-1~q3,
                             randomizer_x==-1&randomizer_y==1~q2,
                             randomizer_x==-1&randomizer_y==-1~q4),
         random_q2=case_when(randomizer_x==1&randomizer_y==1~q2,
                             randomizer_x==1&randomizer_y==-1~q4,
                             randomizer_x==-1&randomizer_y==1~q1,
                             randomizer_x==-1&randomizer_y==-1~q3),
         random_q3=case_when(randomizer_x==1&randomizer_y==1~q3,
                             randomizer_x==1&randomizer_y==-1~q1,
                             randomizer_x==-1&randomizer_y==1~q4,
                             randomizer_x==-1&randomizer_y==-1~q2),
         random_q4=case_when(randomizer_x==1&randomizer_y==1~q4,
                             randomizer_x==1&randomizer_y==-1~q2,
                             randomizer_x==-1&randomizer_y==1~q3,
                             randomizer_x==-1&randomizer_y==-1~q1))%>%
  mutate(current_quadrant=case_when(randomized_quadrant == 1~random_q1,
                                    randomized_quadrant == 2~random_q2,
                                    randomized_quadrant == 3~random_q3,
                                    randomized_quadrant == 4~random_q4))%>%
  mutate(target_looks=if_else(current_quadrant==target,1,0),
         competitor_looks=if_else(current_quadrant==competitor,1,0),
         dist1_looks=if_else(current_quadrant==distractor_1,1,0),
         dist2_looks=if_else(current_quadrant==distractor,1,0))%>%
  mutate(dist1_looks=if_else(randomise_trials%in% c(2, 3, 4, 5, 7, 11),NA,dist1_looks),
         dist2_looks=if_else(randomise_trials%in% c(2, 3, 4, 5, 7, 11),NA,dist2_looks))%>%
  filter(time_rounded<1000&time_rounded>0)%>%
  filter((randomise_trials %in% c(9, 13)) |
         (randomise_trials %in% c(2, 3, 4, 5, 7, 11) & y_pred_normalised >= 0))%>%
  ungroup()%>%
  mutate(syllable=case_when(time_rounded<200~0,
                            stress_audio=="penultimate" & time_rounded>200 &
                              time_rounded<penn_times[1]~1,
                            stress_audio=="penultimate" & time_rounded>=penn_times[1] &
                              time_rounded<mean(penn_times[2],penn_times[3]) ~2,
                            stress_audio=="penultimate" & time_rounded<=penn_times[3]~3,
                            stress_audio=="antipenultimate" & time_rounded>200 &
                              time_rounded<anti_times[1]~1,
                            stress_audio=="antipenultimate" & time_rounded>=anti_times[1] &
                              time_rounded<mean(anti_times[2],anti_times[3]) ~2,
                            stress_audio=="antipenultimate" & time_rounded<=anti_times[3]~3))%>%
  filter(time_rounded<1000)%>%
  filter(randomise_trials==13)%>%
  mutate(trials_code=if_else(randomise_trials<6,"non-stress","stress"))

s_exp2_data_all<-s_exp2_data_all%>%filter(correct==1)  
  
ets_exp2_all_agg<-s_exp2_data_all%>%
  group_by(stress_audio,time_rounded,trials_code)%>%
  summarise(mean_target_looks=sum(target_looks),
            mean_competitor_looks=sum(competitor_looks),
            mean_dist1_looks=sum(dist1_looks),
            mean_dist2_looks=sum(dist2_looks))%>%
  ungroup()%>%
  pivot_longer(cols=c(mean_target_looks:mean_dist2_looks),names_to = "names",values_to="values")
  
ets_exp2_all_agg%>%
  ggplot(aes(x=time_rounded,y=values,color=names))+
  geom_point()+
  geom_smooth()+
  facet_grid(factor(stress_audio)~factor(trials_code))

ets_exp2_all_agg_part<-s_exp2_data_all%>%
  filter(time_rounded<800&time_rounded>0)%>%
  group_by(stress_audio,participant.private.id,randomise_trials)%>%
  summarise(mean_target_looks=mean(target_looks),
            mean_competitor_looks=mean(competitor_looks),
            mean_dist1_looks=mean(dist1_looks),
            mean_dist2_looks=mean(dist2_looks))%>%
  ungroup()%>%
  pivot_longer(cols=c(mean_target_looks:mean_dist2_looks),names_to = "names",values_to="values")
  
ets_exp2_all_agg_part%>%
  ggplot(aes(x=factor(participant.private.id),y=values,color=names))+
  geom_point()+
  geom_smooth()+
  facet_grid(stress_audio~randomise_trials)+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

```{r}
ets_exp2_all_agg_part_wider<-ets_exp2_all_agg_part%>%
  pivot_wider(names_from = names,values_from = values)%>%
  mutate(proportion_o_looks=mean_target_looks-mean_competitor_looks)%>%
  left_join(battery_agg_wider_simp)%>%
  left_join(digit_cleaned_simp)%>%
  left_join(lextale_agg_cleaned_simp)%>%
  left_join(italian_lextale_agg_cleaned_simp)%>%
  left_join(autism_cleaned)


ets_exp2_all_agg_part_wider%>%
  ggplot(aes(x=stress_audio,y=proportion_o_looks,color=stress_audio))+
  geom_boxplot()+
  geom_jitter()+
  facet_grid(.~randomise_trials)+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
full_data_exp2<-ets_exp2_all_agg_part_wider%>%
  select(!c(participant.private.id,c_battery_up_dur:c_battery_up_risetime,
            mean_target_looks:mean_dist2_looks))
full_data_exp2$randomise_trials<-as.factor(full_data_exp2$randomise_trials)
ggpairs(full_data_exp2)
```

```{r message=FALSE, warning=FALSE}
force_var <- "stress_audio"
force_in_vector
force_in_vector <- rep(FALSE,28)  # Assuming 28 variables as in your output
names(force_in_vector) <- colnames(full_data_exp2)  # Make sure this matches your data structure
force_in_vector["stress_play"] <- TRUE
# Exclude the response and the forced variable from the predictors
predictors <- setdiff(names(full_data_exp2), c("proportion_o_looks", force_var))

# Create the formula ensuring 'stress_play' is always included
formula_interactions <- as.formula(paste("proportion_o_looks ~ (", force_var, "+", paste(predictors, collapse = "+"), ")^2"))
formula_interactions

subset_fit <- regsubsets(formula_interactions, data = full_data_exp2, nbest = 1, nvmax = 10, force.in = force_in_vector,really.big=T)

subset_summary <- summary(subset_fit)
subset_summary

# Print summary statistics
subset_summary$adjr2
subset_summary$cp
subset_summary$bic

# Choose a model based on BIC
selected_model <- which.min(subset_summary$bic)
subset_summary$which[selected_model, ]

# Cross-validation to check model performance
fit_control <- trainControl(method = "cv", number = 10)  # 10-fold cross-validation
fit_control
```

```{r}
included_predictors <- names(subset_summary$which[selected_model, ][subset_summary$which[selected_model, ] & names(subset_summary$which[selected_model, ]) != "(Intercept)"])

formula_str <- "proportion_o_looks ~"
formula_str <- paste(formula_str, paste(included_predictors, collapse = " + "), sep = "")
formula_str

formula_str <- gsub("penultimate", "", formula_str, perl = TRUE)
formula_str <- gsub("13", "", formula_str, perl = TRUE)
formula_str <- gsub("11", "", formula_str, perl = TRUE)
formula_str <- gsub("7", "", formula_str, perl = TRUE)
model_formula <- as.formula(formula_str)
model_lm2 <- lm(model_formula, data = ets_exp2_all_agg_part_wider)

# Display the summary of the model
summary(model_lm2)

check_model(m1)
check_model(model_lm)
```

```{r}
coef_df2 <- summary(model_lm2)$coefficients

coef_df2 <- as.data.frame(coef_df2)
coef_df2$Predictor <- rownames(coef_df2)
rownames(coef_df2) <- NULL

ci_level <- 1.96
coef_df2$CI_Lower <- coef_df2$Estimate - ci_level * coef_df2$`Std. Error`
coef_df2$CI_Upper <- coef_df2$Estimate + ci_level * coef_df2$`Std. Error`


ggplot(coef_df2, aes(x = Predictor, y = Estimate, ymin = CI_Lower, ymax = CI_Upper)) +
  geom_pointrange() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(title = "Effect Sizes and Confidence Intervals for Model Coefficients",
       x = "Predictors",
       y = "Estimate") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+coord_flip()+theme_bw()
```
